spring:
  application:
    name: phoenix-code
  datasource:
    url: jdbc:postgresql://localhost:5432/otp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls:
      enable: true
  username:
    USERNAME
  password:
    PASS

smpp:
  host: smpp.example.com
  port: 2775
  systemId: yourSystemId
  password: yourPassword
  systemType: ""
  sourceAddr: "YOUR_SENDER_ID"
  addrTon: 1
  addrNpi: 1

telegram:
  token: YOUR_TOKEN